### ISSUE TITLE
ir_tx/philips.py - data value validation

### ISSUE THREAD

**Issue by max-m-s** [peterhinch/micropython_ir#17]
In RC5, I believe up to 7F (127) should be acceptable. It seems to work if it's changed from 3F:

```
class RC5(IR):
    valid = (0x1f, 0x3f, 1)  # Max addr, data, toggle
```

**Comment by peterhinch** [comment]
You are right - thank you. I supported RC5X in the code but forgot to change the validation. Will fix.
