### ISSUE TITLE
Use MicroPython ESP32 port RMT built-in carrier?

### ISSUE THREAD

**Issue by water5** [peterhinch/micropython_ir#2]
MicroPython ESP32 port RMT support carrier now, can you update the code to use esp32.RMT built-in carrier function?

**Comment by peterhinch** [comment]
I'm aware of this and it's on my todo list.

**Comment by peterhinch** [comment]
I have pushed an update which fixes this. 

The transmitter test program is also updated for `uasyncio` V3, so if you use this you will need to check the docs as its dependencies have changed.

Please report back on any testing, or if you have any comment on code or docs.
