### ISSUE TITLE
Info: Some IR protocols and remotes

### ISSUE THREAD

**Issue by marble** [peterhinch/micropython_ir#24]
Wow, cool stuff Peter, I started with punchcards too and I'm amazed as well that we can run functions on a 5 Dollar ESP32 that may have required as super computer back then.

Just to add some information that may come in handy for you or somebody:

* https://www.mikrocontroller.net/articles/IRMP#IR-Protokolle (german, probably the original)
* https://www.mikrocontroller.net/articles/IRMP_-_english#IR_Protocols (english, hopefully fully translated)

Keep on and enjoy!

**Comment by peterhinch** [comment]
Thank you - an interesting summary. I've added a link in README.md.
