### ISSUE TITLE
Allowing repeat NEC codes

### ISSUE THREAD

**Issue by PajamaSLAM** [peterhinch/micropython_ir#25]
Hello,

Thank you for this library! 

I am trying to use this library on a Raspberry Pi Pico running the latest stable MicroPython.It properly decodes my IR remote codes: I am trying to allow repeat codes to send the last known received code (for Volume up and down, for example). Looking through the nec.py and the *args notation in the docs, I believe it is possible to specify but I cannot seem to make it work correctly. I get Traceback errors when I attempt to add the *arg "0" to the ir function. I have a little coding experience but overall I am quite new to this, so I apologize if this is in the wrong spot.

Thank you very much,
Mike

**Comment by peterhinch** [comment]
Hi Mike,
the NEC protocol periodically sends a REPEAT signal if a key is held down. My driver returns a data value of -1 each time this occurs. So, if you hold down the "volume up" key you will get VOLUME_UP...REPEAT...REPEAT...REPEAT. In this instance your code needs to run the `increase_volume` method four times.
