### ISSUE TITLE
Corrupted transmission on RP2 during heavy load

### ISSUE THREAD

**Issue by ThinkTransit** [peterhinch/micropython_ir#40]
When the RP2 is under heavy load (high cpu/irq activity) it is possible for the the PIO interrupts which feed the transmit buffer to be delayed, resulting in malformed IR signals. This is particularly evident when wifi is active and data is is being transferred.

In the worst case delays of up to 30ms can be experienced.

Suggest that the existing PIO routines could be fed using DMA rather than interrupts.

**Comment by peterhinch** [comment]
I'll close this as I think we've fixed the problem.
