### ISSUE TITLE
Error in playback code in TRANSMITTER.md

### ISSUE THREAD

**Issue by bluepole** [peterhinch/micropython_ir#43]
Small error (editing oversight?) in the playback code in the 'Unsupported Protocols' section where the ESP32 pin is diefined as a 2-tuple rather than an actual Pin. Otherwise good!

**Comment by peterhinch** [comment]
Thanks for the report. The error I can see in `RECEIVER.md` section 8 is that
```py
from ir_rx import NEC_16
```
should read
```py
from ir_rx.nec import NEC_16
```
Is this the issue you're reporting?

**Comment by bluepole** [comment]
Sorry no - this is the line in the playback code...

`pin = (Pin(23, Pin.OUT, value = 0), Pin(21, Pin.OUT, value = 0))
`

Should be a simple Pin, not a tuple, I think. Anyway, that's what works! Love the project BTW.

**Comment by peterhinch** [comment]
Ah, got it! Thanks for the report: now fixed.
